framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(resolve:REDIS_DSN)%'
        pools:
            app.cache.rates:
                adapter: cache.adapter.redis
                default_lifetime: 120
