version: '3'

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/currency-exchanger
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php83-service
  php83-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php83-container
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/currency-exchanger
  redis-service:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server
    restart: unless-stopped



